apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tanzu-kubernet-cluster
  namespace: ns-tanzu
spec:
  topology:
    controlPlane:
      vmClass: guaranteed-small
      replicas: 1
      storageClass: avi-policy
      tkr: 
        reference:
          name: v1.16.8---vmware.1-tkg.3.60d2ffd
    nodePools:
    - name: worker-pool
      vmClass: guaranteed-small
      replicas: 1
      storageClass: avi-policy
      tkr: 
        reference:
          name: v1.16.8---vmware.1-tkg.3.60d2ffd
      
