apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tanzu-kubernet-cluster
spec:
  distribution:
    version: v1.21
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: avi-policy
    workers:
      class: guaranteed-small
      count: 1
      storageClass: avi-policy
  settings:
    storage:
      classes: ["avi-policy"]              #Named PVC storage classes
      defaultClass:  avi-policy   #Default PVC storage class
