apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tanzu-kubernet-cluster
  namespace: tanzu-test-by-patrick
spec:
  topology:
    controlPlane:
      vmClass: guaranteed-small
      replicas: 1
      storageClass: avi-policy
      tkr: 
        reference:
          name: v1.20.7---vmware.1-tkg.1.7fb9067
    nodePools:
    - name: worker-pool-1
      vmClass: guaranteed-small
      replicas: 1
      storageClass: avi-policy
      tkr: 
        reference:
          name: v1.20.7---vmware.1-tkg.1.7fb9067
      
